---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
      - 'release'

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: debug home
        run: |
          echo "$PWD"
          echo "$HOME"
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: compile go examples
        run: |
          make build
