---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"
      - "release"

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - name: debug home
        run: |
          echo "$PWD"
          echo "$HOME"
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: compile go examples
        run: |
          make build
